language: node_js
node_js:
  - "4"
before_install:
  - "npm install rmasterbot -g"
  - "npm install chai -g"
  - "npm install mocha -g"
  - "npm install sinon -g"
  - "rmbot install pinterest -s"
script:
  - cd /home/travis/.nvm/versions/node/v4.8.2/lib/node_modules/rmasterbot/
  - mocha test/bots/pinterest --recursive