language: node_js
node_js:
  - "4"
before_install:
  - "npm install rmasterbot -g"
  - "rmbot install $TRAVIS_BUILD_DIR -s"
script:
  - cd $HOME/rmasterbot
  - mocha test/bots/pinterest --recursive